# Generated by Django 4.1.7 on 2023-03-24 16:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=122)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("phone", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=122)),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photography"),
                            ("video", "Videography"),
                            ("decor", "Decoration"),
                            ("catering", "Catering"),
                        ],
                        max_length=20,
                    ),
                ),
                ("header", models.CharField(max_length=122)),
                ("desc", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("city", models.CharField(blank=True, default="", max_length=255)),
                ("state", models.CharField(default="", max_length=255)),
                (
                    "featured_package_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("organizer", models.CharField(default="", max_length=122)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="service_images/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeddingBooking",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date_booked", models.DateTimeField(auto_now_add=True)),
                (
                    "featured_package_price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("pending", "Pending"), ("paid", "Paid")],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookingApp.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookingApp.service",
                    ),
                ),
            ],
        ),
    ]
